pipeline {
    agent any
    stages {
        stage('Build') { 
            agent {
                docker {
                    image 'node:20.9.0-alpine3.18' 
                    args '-p 3000:3000' 
                }
            }
            steps {
                dir('jenkins-data/simple_app'){
                    sh 'npm install' 
                }
                
            }
        }

        stage("Unit Test") {
            agent {
                docker {
                    image 'node:20.9.0-alpine3.18' 
                    args '-p 3000:3000' 
                }
            }
            steps {
                dir('jenkins-data/simple_app'){
                    sh 'npm test'
                }
            }
        }

        stage("Regression Test") {
            agent {
                docker {
                    image 'node:20.9.0-alpine3.18' 
                    args '-p 3000:3000' 
                }
            }
            steps {
                dir('jenkins-data/simple_app'){
                    sh 'echo \'Regression test\''
                }
            }
        }
        stage('OWASP DependencyCheck') {
            agent any
			steps {
				dir('jenkins-data/simple_app'){
					dependencyCheck additionalArguments: '--format HTML --format XML', odcInstallation: 'DPCheck'
				}
			}
		}

    }
    post {
		success {
            
			dependencyCheckPublisher pattern: 'jenkins-data/simple_app/dependency-check-report.xml'
            
		}
	}
}
